apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddeploy
  labels:
    app: backend-deployment
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        name: backend-pod
        app: backend-pod
    spec:
      containers: 
      - name: backend
        image: ninjaleo/backend:latest
        ports:
        - containerPort: 80
