apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backenddeploy
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        name: backend
        app: backendapp
    spec:
      containers: 
      - name: backend
        image: ninjaleo/backend:latest
        ports:
        - containerPort: 3001
