apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backenddeploy
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers: 
      - name: frontend
        image: ninjaleo/backend:latest
      tolerations:
        - key: "name"
          operation: "Equal"
          value: "ninja"
          effect: "NoSchedule"
        ports:
        - containerPort: 3001
