apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 80
      protocol: TCP
  selector:
    name: backend
    app: backendapp
  
