apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node-service
spec:
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 80
      protocol: TCP
  selector:
    app: backend-pod
  
